version: '3'

services:

  reverse-proxy:
    image: reverse_proxy
    container_name: reverse_proxy_a1
    build:
      context: ./reverse_proxy
    depends_on:
      - server
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
     - 80:80

  server:
    image: server
    container_name: server_container_a1
    build:
      context: ./server
    ports:
    # Map port 8080 to run on port 80 in container
     - 8080:80
    restart: on-failure